variables:
  # variable de grupo de artifactory
  - group: artifactory-produccion
  # Propiedad del sonarQube para indicar el directorio a analizar
  - name: sonarSources
    value: 'CanalContingenciaBLE/src/main'
  # propiedad de sonarQube para indicar los directorios a excluir en el análisis
  - name: sonarExclusions
    value: ''
  # 1=proyecto nuevo en sonarQube y 0=para actualizar una rama nueva del proyecto existente en sonarQube
  - name: sonarCreateMaster
    value: '1'
  # Nombre del service connection para tarea de sonarQube
  - name: sonarQubeServiceEndpoint
    value: 'SonarLts'
  # Nombre del service connection de sonarQube para tarea de gradle o maven
  - name: sonarQubeServiceEndpointGeneric
    value: 'Sonar-Generic-Lts'
  # nombre de la tarea para compilar en Gradle
  - name: taskCommand
    value: 'build -x test compileTestJava'
  # Ruta donde se encuentra el gradleWrapperFile en el proyecto
  - name: gradleWPath
    value: '$(System.DefaultWorkingDirectory)/CanalContingenciaBLE/gradlew'
  # Ruta de directorio de trabajo, si no tiene un directorio diferente no cambie el valor por defecto establecido.
  - name: gradleWorkingDirectory
    value: '$(System.DefaultWorkingDirectory)/CanalContingenciaBLE'

resources:
  repositories:
    - repository: template
      type: git
      name: DevOps/_git/templates-yaml
      ref: 'refs/heads/master' # indicamos la rama que apuntamos en el repositorios template-yaml, siempre debemos apuntar a master
trigger:
  branches:
    include:
      - trunk
  paths:
    include:
      - 'feature/*'

name: $(date:yyyyMMdd)$(rev:.r)
stages:
  - stage:
    jobs:
      - job:
        pool:
          name: Banistmo-Windows-Pool
        workspace:
          clean: resources
        steps:
          - template: build_GRADLE_FUNCTIONAL_TEST_LTS.yml@template #ref en otro repository
            parameters:
              sonarExclusions: ${{variables.sonarExclusions}}
              sonarSources: ${{variables.sonarSources}}
              sonarCreateMaster: ${{variables.sonarCreateMaster}}
              sonarQubeServiceEndpoint: ${{variables.sonarQubeServiceEndpoint}}
              sonarQubeServiceEndpointGeneric: ${{variables.sonarQubeServiceEndpointGeneric}}
              taskCommand: ${{variables.taskCommand}}
              gradleWPath: ${{variables.gradleWPath}}
              gradleWorkingDirectory: ${{variables.gradleWorkingDirectory}}
